import type { Mood, MoodMeta } from "../types.ts";

/**
 * Per-mood timbral + harmonic configuration. Values must match the inline
 * `MOOD_META` definition in `index.html` until the inline script is
 * removed in a later phase.
 */
export const MOOD_META: Record<Mood, MoodMeta> = {
  rainy: {
    bpmRange: [62, 72],
    swingRange: [0.07, 0.12],
    names: ["grey afternoon", "window seat", "soft rain"],
    key_pool: [0, 2, 3, 5, 9],
    reverb: { dur: 3.2, decay: 0.5 },
    snareFreq: 2200,
    snareQ: 0.5,
    bassFilter: 280,
    bassAttack: 0.02,
    compTimbre: "rhodes",
    melTimbre: "rhodes",
    ambience: "rain",
    improv: {
      peakDensityCap: 0.75,
      bridgeSubstitutions: [
        [10, "maj7"],
        [5, "min9"],
        [3, "maj9"],
        [8, "dom9"],
      ],
      voices: ["rhodes", "vibraphone"],
      breakoutThreshold: 0.72,
    },
  },
  late: {
    bpmRange: [65, 75],
    swingRange: [0.06, 0.1],
    names: ["3am brew", "city lights", "last bus"],
    key_pool: [0, 2, 5, 7, 9],
    reverb: { dur: 4.0, decay: 0.42 },
    snareFreq: 2600,
    snareQ: 0.7,
    bassFilter: 200,
    bassAttack: 0.03,
    compTimbre: "vibraphone",
    melTimbre: "vibraphone",
    ambience: "traffic",
    improv: {
      peakDensityCap: 1.0,
      bridgeSubstitutions: [
        [2, "min7b5"],
        [7, "dom9"],
        [0, "min9"],
        [5, "maj9"],
      ],
      voices: ["vibraphone", "bell"],
      breakoutThreshold: 0.62,
    },
  },
  cafe: {
    bpmRange: [70, 80],
    swingRange: [0.04, 0.07],
    names: ["warm espresso", "cosy corner", "notebook"],
    key_pool: [0, 4, 5, 7, 9],
    reverb: { dur: 1.4, decay: 0.72 },
    snareFreq: 3000,
    snareQ: 0.9,
    bassFilter: 400,
    bassAttack: 0.01,
    compTimbre: "guitar",
    melTimbre: "rhodes",
    ambience: "room",
    improv: {
      peakDensityCap: 1.0,
      bridgeSubstitutions: [
        [9, "min7"],
        [2, "dom9"],
        [7, "maj9"],
        [0, "maj7"],
      ],
      voices: ["rhodes", "vibraphone"],
      breakoutThreshold: 0.68,
    },
  },
  sleepy: {
    bpmRange: [55, 65],
    swingRange: [0.09, 0.14],
    names: ["almost asleep", "blanket hour", "dim lamp"],
    key_pool: [0, 2, 3, 5, 8],
    reverb: { dur: 5.0, decay: 0.35 },
    snareFreq: 1800,
    snareQ: 0.4,
    bassFilter: 180,
    bassAttack: 0.04,
    compTimbre: "pad",
    melTimbre: "celesta",
    ambience: "wind",
    improv: {
      peakDensityCap: 0.65,
      bridgeSubstitutions: [
        [10, "maj9"],
        [3, "maj7"],
        [8, "maj7"],
        [5, "min9"],
      ],
      voices: ["celesta", "bell"],
      breakoutThreshold: 0.78,
    },
  },
  transit: {
    bpmRange: [60, 70],
    swingRange: [0.08, 0.13],
    names: ["platform 4", "last departure", "signal hold"],
    key_pool: [0, 2, 3, 5, 8],
    reverb: { dur: 7.0, decay: 0.55 },
    snareFreq: 2000,
    snareQ: 0.45,
    bassFilter: 220,
    bassAttack: 0.03,
    compTimbre: "coldsynth",
    melTimbre: "bell",
    ambience: "transit",
    improv: {
      peakDensityCap: 0.9,
      bridgeSubstitutions: [
        [10, "min7"],
        [5, "min7"],
        [8, "dom9"],
        [3, "maj9"],
      ],
      voices: ["bell", "vibraphone"],
      breakoutThreshold: 0.65,
    },
  },
};
